#!/usr/bin/perl

use strict;
use warnings;
use 5.010;

use JSON;
use YAML;
use Module::Load;
use lib 'lib';
use autoreddit;
use autouse 'Data::Dumper' => 'Dumper';

my $config = YAML::LoadFile('config.yaml');
my $autoreddit = autoreddit->new([qw( Download Log )]);
my $links = autoreddit->get_saved($config->{ saved_url });
my $urls = [ map { $_->{ data }{ url } }
			@{$links->{ data }{ children } } ];

for(@$urls){ $autoreddit->process($_);}
