#!/usr/bin/perl

use strict;
use warnings;
use 5.010;

use JSON;
use YAML;
use Module::Load;
use lib 'lib';
use autoreddit;

my $config = YAML::LoadFile('config.yaml');
my $links = autoreddit->get_saved_links($config);

use Data::Dumper;
print Dumper($links);
